Repository binbashar/le-genai-ml, pull requests merged in 2024-07, with the labels that each got.

#4 Feature | genai-llm-rag-bedrock-poc
  genai-llm-rag-bedrock-poc/.DS_Store
  genai-llm-rag-bedrock-poc/Dockerfile
  genai-llm-rag-bedrock-poc/README.md
  genai-llm-rag-bedrock-poc/app.py
  genai-llm-rag-bedrock-poc/cases/__init__.py
  genai-llm-rag-bedrock-poc/cases/code_generation.py
  genai-llm-rag-bedrock-poc/cases/extract_text_from_files.py
  genai-llm-rag-bedrock-poc/cases/translation_nlp.py
  genai-llm-rag-bedrock-poc/requirements.txt
Labels: feature, minor

#3 Enhancement | Add standard files and workflows for binbash open source repos
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release-management-github.yml
  .github/workflows/test-lint-black.yaml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  LICENSE.txt
Labels: enhancement, patch

#5 Fix | Minor fixes and updating README.md
  assets/images/genai-llm-rag-bedrock-poc.png
  genai-llm-rag-bedrock-poc/Dockerfile
  genai-llm-rag-bedrock-poc/README.md
  genai-llm-rag-bedrock-poc/app.py
Labels: fix, patch
